### ISSUE TITLE
Hey I get an error when compiling the script

### ISSUE THREAD

**Issue by Antonius-A** [msr8/attiny85#1]
DigiKeyboard.h: No such file or directory

fatal error: DigiKeyboard.h: No such file or directory
 #include "DigiKeyboard.h"
          ^~~~~~~~~~~~~~~~
compilation terminated.

exit status 1

Compilation error: DigiKeyboard.h: No such file or directory

Any ideas what could be causing that?

**Comment by msr8** [comment]
It seems like the attiny85 drivers(?) cannot be accessed. In the Arduino IDE, you gotta go to the preferences/settings and add "http://digistump.com/package_digistump_index.json" in the "Additional boards manager URLs" like so:

![Screenshot 2024-01-01 at 11 22 16 AM](https://github.com/msr8/attiny85/assets/79649185/36d9a1f5-e035-487c-994a-3af2c5c71b45)

(In this screenshot I am using Arduino IDE 2.2.1)

Does this get rid of the error?

**Comment by msr8** [comment]
For anyone else having this issue, the previous mentioned link is dead. Here is another working URL: https://raw.githubusercontent.com/digistump/arduino-boards-index/master/package_digistump_index.json
